module.exports ={SOCKET_EVENT : {
  NEW_TRIP:"NEW_TRIP",
  NEW_TRIP_ERROR : "NEW_TRIP_ERROR",
  UPDATE_TRIP:"UPDATE_TRIP",
  UPDATE_TRIP_ERROR : "UPDATE_TRIP_ERROR",
  DELETE_TRIP:"DELETE_TRIP",
  DELETE_TRIP_ERROR : "DELETE_TRIP_ERROR"
}};